### ISSUE TITLE
GitHub install error

### ISSUE THREAD

**Issue by HedvigS** [fkeck/phylosignal#15]
While waiting on #14 , I tried installing from github but it fails like this:

Any ideas? I think it's got to do with xcode and macos. I'm on a work computer, I can't install Xcode updates on my own but I'll get the IT guy to do it tmrw.

```

> devtools::install_github("fkeck/phylosignal", ref = "v1.2")
Downloading GitHub repo fkeck/phylosignal@v1.2
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                           
 2: CRAN packages only                            
 3: None                                          
 4: askpass      (1.1        -> 1.2.0     ) [CRAN]
 5: cpp11        (0.4.4      -> 0.4.6     ) [CRAN]
 6: purrr        (1.0.1      -> 1.0.2     ) [CRAN]
 7: openssl      (2.1.0      -> 2.1.1     ) [CRAN]
 8: curl         (5.0.1      -> 5.0.2     ) [CRAN]
 9: dplyr        (1.1.2      -> 1.1.3     ) [CRAN]
10: uuid         (1.1-0      -> 1.1-1     ) [CRAN]
11: httr         (1.4.6      -> 1.4.7     ) [CRAN]
12: prettyunits  (1.1.1      -> 1.2.0     ) [CRAN]
13: RcppArmad... (0.12.4.1.0 -> 0.12.6.4.0) [CRAN]
14: igraph       (1.5.0      -> 1.5.1     ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
askpass      (1.1        -> 1.2.0     ) [CRAN]
cpp11        (0.4.4      -> 0.4.6     ) [CRAN]
purrr        (1.0.1      -> 1.0.2     ) [CRAN]
openssl      (2.1.0      -> 2.1.1     ) [CRAN]
curl         (5.0.1      -> 5.0.2     ) [CRAN]
dplyr        (1.1.2      -> 1.1.3     ) [CRAN]
uuid         (1.1-0      -> 1.1-1     ) [CRAN]
httr         (1.4.6      -> 1.4.7     ) [CRAN]
prettyunits  (1.1.1      -> 1.2.0     ) [CRAN]
RcppArmad... (0.12.4.1.0 -> 0.12.6.4.0) [CRAN]
igraph       (1.5.0      -> 1.5.1     ) [CRAN]
Skipping 1 packages not available: adephylo
Installing 11 packages: askpass, cpp11, purrr, openssl, curl, dplyr, uuid, httr, prettyunits, RcppArmadillo, igraph
Installing packages into ‘/Users/skirgard/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/askpass_1.2.0.tgz'
Content type 'application/x-gzip' length 24536 bytes (23 KB)
==================================================
downloaded 23 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/cpp11_0.4.6.tgz'
Content type 'application/x-gzip' length 294426 bytes (287 KB)
==================================================
downloaded 287 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/purrr_1.0.2.tgz'
Content type 'application/x-gzip' length 524515 bytes (512 KB)
==================================================
downloaded 512 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/openssl_2.1.1.tgz'
Content type 'application/x-gzip' length 2888359 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/curl_5.0.2.tgz'
Content type 'application/x-gzip' length 811873 bytes (792 KB)
==================================================
downloaded 792 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/dplyr_1.1.3.tgz'
Content type 'application/x-gzip' length 1589767 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/uuid_1.1-1.tgz'
Content type 'application/x-gzip' length 73464 bytes (71 KB)
==================================================
downloaded 71 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/httr_1.4.7.tgz'
Content type 'application/x-gzip' length 474940 bytes (463 KB)
==================================================
downloaded 463 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/prettyunits_1.2.0.tgz'
Content type 'application/x-gzip' length 155804 bytes (152 KB)
==================================================
downloaded 152 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/RcppArmadillo_0.12.6.4.0.tgz'
Content type 'application/x-gzip' length 1685430 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/igraph_1.5.1.tgz'
Content type 'application/x-gzip' length 9383188 bytes (8.9 MB)
==================================================
downloaded 8.9 MB


The downloaded binary packages are in
	/var/folders/2r/drwc5p6n26ncm5cws9qsntrw0000gr/T//RtmpraLYJ2/downloaded_packages
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/2r/drwc5p6n26ncm5cws9qsntrw0000gr/T/RtmpraLYJ2/remotes9c16418f9d59/fkeck-phylosignal-6ec3beb/DESCRIPTION’ (338ms)
─  preparing ‘phylosignal’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘phylosignal_1.2.tar.gz’
   
Installing package into ‘/Users/skirgard/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘phylosignal’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 12.0.0 (clang-1200.0.31.1)’
using SDK: ‘MacOSX11.0.sdk’
clang++ -arch x86_64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/skirgard/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/skirgard/Library/R/x86_64/4.3/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/skirgard/Library/R/x86_64/4.3/library/Rcpp/include' -I'/Users/skirgard/Library/R/x86_64/4.3/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c signaltest.cpp -o signaltest.o
clang++ -arch x86_64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o phylosignal.so RcppExports.o signaltest.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phylosignal.so] Error 1
ERROR: compilation failed for package ‘phylosignal’
* removing ‘/Users/skirgard/Library/R/x86_64/4.3/library/phylosignal’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/2r/drwc5p6n26ncm5cws9qsntrw0000gr/T//RtmpraLYJ2/file9c1638b9c9b6/phylosignal_1.2.tar.gz’ had non-zero exit status
```

**Comment by fkeck** [comment]
Hi HedvigS,
Could you solve the issue with your IT?
I don't think there is something I can do on my side.
#14 is still on progress.

**Comment by HedvigS** [comment]
> Hi HedvigS, Could you solve the issue with your IT? I don't think there is something I can do on my side. #14 is still on progress.

Yes, out IT guy did xcode etc updates and now it seems like things are working.

Hoping for CRAN again soon :)

**Comment by HedvigS** [comment]
(I take that back, still issues but I'll get our IT-department on it.
Seems like maybe it's similar to this: https://github.com/drieslab/Giotto/issues/441 )

**Comment by HedvigS** [comment]
@fkeck can you tell me what GNU Fortran compiler phylosignal wants? I think it's 12.2.0 but if it's lower that'd be good to know.

**Comment by fkeck** [comment]
It should work with v12.2.0. This is the version used by CRAN to make tests on MacOS.

**Comment by HedvigS** [comment]
> It should work with v12.2.0. This is the version used by CRAN to make tests on MacOS.

Thanks! 
My employer insists on the IT staff installing everything for me, so I'll wait until they're available and then install v12.2.0 and we'll see. that should solve it :)!
